Repository TASK-FORCE/mannalga-api, pull requests merged in 2021-04, with the labels that each got.

#398 모입 게시판 사진첨부 수정 API 개선
  src/course/rest/club/board/ClubBoard.http
  src/course/rest/user/user.http
  src/main/kotlin/com/taskforce/superinvention/app/domain/club/ClubService.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/club/album/image/ClubAlbumImageService.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/club/board/ClubBoardService.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/club/board/comment/ClubBoardCommentRepository.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/club/board/img/ClubBoardImg.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/club/board/img/ClubBoardImgRepository.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/club/board/img/ClubBoardImgService.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/common/image/resize/strategy/GifResizeStrategy.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/common/image/webp/convert/WebpConvertService.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/common/image/webp/convert/handler/Gif2WebpHandler.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/common/image/webp/convert/handler/WebpAnimatedWriter.kt
  src/main/kotlin/com/taskforce/superinvention/app/web/dto/club/board/ClubBoardDto.kt
  src/main/kotlin/com/taskforce/superinvention/app/web/dto/club/board/img/ClubBoardImgDto.kt
  src/main/kotlin/com/taskforce/superinvention/common/config/async/AsyncConfig.kt
  src/test/kotlin/com/taskforce/superinvention/app/domain/club/ClubServiceTest.kt
  src/test/kotlin/com/taskforce/superinvention/app/domain/club/board/ClubBoardServiceTest.kt
  src/test/kotlin/com/taskforce/superinvention/document/club/board/ClubBoardDocumentation.kt
Labels: WIP

#401 변수 네이밍 컨벤션 통합
  src/main/kotlin/com/taskforce/superinvention/app/web/dto/club/ClubDto.kt
  src/test/kotlin/com/taskforce/superinvention/document/club/ClubDocumentation.kt
  src/test/kotlin/com/taskforce/superinvention/document/club/ClubInfoDocumentation.kt
Labels: bug

#405 취소한 만남신청까지 같이 조회하는 버그 수정
  src/course/rest/user/user.http
  src/main/kotlin/com/taskforce/superinvention/app/domain/meeting/MeetingApplicationRepository.kt
  src/main/kotlin/com/taskforce/superinvention/app/domain/meeting/MeetingService.kt
Labels: bug

#406 Spring Security Exception 발생시 Exception Handler를 탈 수 있도록 구현
  src/course/rest/http-client.env.json
  src/main/kotlin/com/taskforce/superinvention/common/advice/GlobalAdviceController.kt
  src/main/kotlin/com/taskforce/superinvention/common/config/security/FilterChainExceptionHandler.kt
  src/main/kotlin/com/taskforce/superinvention/common/config/security/JwtTokenProvider.kt
  src/main/kotlin/com/taskforce/superinvention/common/config/security/WebSecurityConfig.kt
Labels: configuration

#413 만남 신청 조인을 잘못하고 있던 코드 수정
  src/main/kotlin/com/taskforce/superinvention/app/domain/meeting/MeetingApplicationRepository.kt
Labels: asap, bug

#418 JPA Build Configuration for Lazy loading
  build.gradle.kts
Labels: configuration
